name: Daily OpenSearch Sync - psc-recon-devices-match-missing

on:
  schedule:
    # 7:00 PM UTC = 3:00 AM PH Time (PHT)
    - cron: '0 19 * * *'
  workflow_dispatch: # Para pwedeng i-run nang manual pa rin

jobs:
  sync-data:
    runs-on: payconnect-arc-runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Create Auth File
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service-account.json

      - name: Run Script
        env:
          OPENSEARCH_URL: ${{ secrets.OPENSEARCH_URL }}
          OPENSEARCH_USERNAME: ${{ secrets.OPENSEARCH_USERNAME }}
          OPENSEARCH_PASSWORD: ${{ secrets.OPENSEARCH_PASSWORD }}
          GOOGLE_SHEET_ID_INPUT: ${{ secrets.GOOGLE_SHEET_ID_INPUT }}
          INDEX_NAME_INPUT: ${{ secrets.INDEX_NAME_INPUT }}
        run: node upsert-input.js
